### ISSUE TITLE
Running on Java 12

### ISSUE THREAD

**Issue by madamedefarge** [wvengen/proguard-maven-plugin#100]
I am trying to run version 2.1.1 on java 12 but failing at the <libs><lib>...</lib></libs> definition.

Specifically if I use;-

<lib>${java.home}/jmods/java.base.jmod</lib> I get this error;-

 [proguard] Error: Can't read [C:\Program Files\Java\jdk-12.0.1\jmods\java.base.jmod] (Can't process class [module-info.class] (Unsupported version number [56.0] (maximum 54.0, Java 10)))

But if I try to filter module-info.class by using this;-
<lib>${java.home}/jmods/java.base.jmod(!module-info.class)</lib> 

I get this error;-

 [proguard] Error: Can't read [C:\Program Files\Java\jdk-12.0.1\jmods\java.base.jmod(!module-info.class)] (No such file or directory: C:\Program Files\Java\jdk-12.0.1\jmods\java.base.jmod(!module-info.class))

Please can you give a working example of using Java 10, 11 or 12

Thanks.

**Comment by lasselindqvist** [comment]
Try changing the default Proguard version to 6.1.1 by putting this into configuration and let me know what happens

                <dependencies>
                    <dependency>
                        <groupId>net.sf.proguard</groupId>
                        <artifactId>proguard-base</artifactId>
                        <version>6.1.1</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>

**Comment by madamedefarge** [comment]
Thank you! That worked!
