### ISSUE TITLE
java 9 jar read issue

### ISSUE THREAD

**Issue by Grypse** [wvengen/proguard-maven-plugin#101]
can't read jar with java 9 build.

**Comment by lasselindqvist** [comment]
I am happy to help, but please provide the following: possible stacktrace when running Maven with the proper command line switches, example project and what was the expected result and how it differed from the actual.

**Comment by Grypse** [comment]
proguard maven property：
`            <plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
                <version>2.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>proguard</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <proguardVersion>5.3.3</proguardVersion>
                    <injar>${project.build.finalName}.jar</injar>
                    <outjar>${project.build.finalName}.jar</outjar>
                    <obfuscate>true</obfuscate>
                    <options>
                        <option>-dontshrink</option>
                        <option>-dontoptimize</option>
                        
                        <option>-adaptclassstrings</option>
                        
                        <option>-keepattributes Exceptions,InnerClasses,Signature,Deprecated,
                            SourceFile,LineNumberTable,*Annotation*,EnclosingMethod
                        </option>
                        <option>-keeppackagenames</option>
                        
                        <option>-keepnames interface **</option>
                        
                        <option>-keepparameternames</option>
                        
                        
                        <option>-keep class !com.slm.proguard.example.spring.boot.controller.ExampleController { *; }
                        </option>
                        <option>-keep class javax.xml.bind.ModuleUtil</option>
                        
                        
                        
                        <option>-keep interface * extends * { *; }</option>
                        
                        <option>-keepclassmembers class * {
                            @org.springframework.beans.factory.annotation.Autowired *;
                            @org.springframework.beans.factory.annotation.Value *;
                            }
                        </option>
                    </options>
                    <libs>
                        
                        <lib>${java.home}/lib/rt.jar</lib>
                        <lib>${java.home}/lib/jce.jar</lib>
                    </libs>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>net.sf.proguard</groupId>
                        <artifactId>proguard-base</artifactId>
                        <version>5.3.3</version>
                    </dependency>
                </dependencies>
            </plugin>`
build error：

>  [proguard] Reading library jar [C:\Users\fredp\.m2\repository\org\aspectj\aspectjweaver\1.9.4\aspectjweaver-1.9.4.jar]
 [proguard] java.io.IOException: Can't read [C:\Users\fredp\.m2\repository\javax\xml\bind\jaxb-api\2.3.1\jaxb-api-2.3.1.jar] (Can't process class [META-INF/versions/9/javax/xml/bind/ModuleUtil.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8)))
 [proguard]     at proguard.InputReader.readInput(InputReader.java:188)
 [proguard]     at proguard.InputReader.readInput(InputReader.java:158)
 [proguard]     at proguard.InputReader.readInput(InputReader.java:136)
 [proguard]     at proguard.InputReader.execute(InputReader.java:88)
 [proguard]     at proguard.ProGuard.readInput(ProGuard.java:218)
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:82)
 [proguard]     at proguard.ProGuard.main(ProGuard.java:538)
 [proguard] Caused by: java.io.IOException: Can't process class [META-INF/versions/9/javax/xml/bind/ModuleUtil.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8))
 [proguard]     at proguard.io.ClassReader.read(ClassReader.java:112)
 [proguard]     at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
 [proguard]     at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
 [proguard]     at proguard.io.JarReader.read(JarReader.java:65)
 [proguard]     at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
 [proguard]     at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
 [proguard]     at proguard.InputReader.readInput(InputReader.java:184)
 [proguard]     ... 6 more
 [proguard] Caused by: java.lang.UnsupportedOperationException: Unsupported class version number [53.0] (maximum 52.0, Java 1.8)
 [proguard]     at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:145)
 [proguard]     at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:89)
 [proguard]     at proguard.classfile.LibraryClass.accept(LibraryClass.java:306)
 [proguard]     at proguard.io.ClassReader.read(ClassReader.java:86)
 [proguard]     ... 12 more

>

**Comment by lasselindqvist** [comment]
Try changing the

	<dependencies>
		<dependency>
			<groupId>net.sf.proguard</groupId>
			<artifactId>proguard-base</artifactId>
			<version>5.3.3</version>
		</dependency>
	</dependencies>

to


	<dependencies>
		<dependency>
			<groupId>net.sf.proguard</groupId>
			<artifactId>proguard-base</artifactId>
			<version>6.1.1</version>
		</dependency>
	</dependencies>

the old proguard version does not support Java 9.

**Comment by Grypse** [comment]
> Try changing the
> 
> ```
> <dependencies>
> 	<dependency>
> 		<groupId>net.sf.proguard</groupId>
> 		<artifactId>proguard-base</artifactId>
> 		<version>5.3.3</version>
> 	</dependency>
> </dependencies>
> ```
> 
> to
> 
> ```
> <dependencies>
> 	<dependency>
> 		<groupId>net.sf.proguard</groupId>
> 		<artifactId>proguard-base</artifactId>
> 		<version>6.1.1</version>
> 	</dependency>
> </dependencies>
> ```
> 
> the old proguard version does not support Java 9.

Ok,Thanks.
