### ISSUE TITLE
Can pass jvm parameters to plugin

### ISSUE THREAD

**Issue by RuiBaiXYZ** [wvengen/proguard-maven-plugin#107]
I want to pass jvm parameters to plugin, but not found any way to .
Eg, -Xmx2G

**Comment by Eric-Tobias** [comment]
That is a parameter for the JVM and isn't related to the plugin itself. You can set compiler arguments using plain Maven. Have a look at: https://www.logicbig.com/tutorials/build-tools/apache-maven/java-compiler-arguments.html. Hope this helps!

**Comment by RuiBaiXYZ** [comment]
In `pom.xml` file, I guess it started another java process to execute proguard. 

```
      <plugin>
        <groupId>com.github.wvengen</groupId>
        <artifactId>proguard-maven-plugin</artifactId>
        <version>${ver.maven.proguard}</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>proguard</goal>
            </goals>
            <configuration>
              ****
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>net.sf.proguard</groupId>
            <artifactId>proguard-base</artifactId>
            <version>${ver.proguard}</version>
          </dependency>
        </dependencies>
      </plugin>
```

In my case, when starting jvm without parameter `-XX:-ReadIPInfoForRAS` java will be to long to reponse. So I want to pass jvm parameters to execute proguard.

**Comment by RuiBaiXYZ** [comment]
I solved with setting jvm global environment variables.
