### ISSUE TITLE
Spring internal libraries variable string value is getting changed

### ISSUE THREAD

**Issue by mageshsrinivasulu** [wvengen/proguard-maven-plugin#110]
Happening in the class org.springframework.cglib.proxy.MethodInterceptorGenerator don't know why. I am trying to configure proguard for spring based application. Is there any way to mention not to change anything in internal library. Is very hard to configure

**Before obfuscator**
`private static final Signature GET_DECLARED_METHODS = TypeUtils.parseSignature("java.lang.reflect.Method[] getDeclaredMethods()");`

**After obfuscator**
`private static final Signature GET_DECLARED_METHODS = TypeUtils.parseSignature("java.lang.reflect.Method");`

**Comment by lasselindqvist** [comment]
You can check the proguard documenation about ignoring things in obfuscation https://www.guardsquare.com/en/products/proguard/manual/examples
