### ISSUE TITLE
UTF-8 encoded strings

### ISSUE THREAD

**Issue by saprophagist** [wvengen/proguard-maven-plugin#121]
While obfuscating UTF-8 encoded Turkish characters are corrupted. When running manually "-Dfile.encoding=UTF-8" parameter works. Is there a way to handle this issue?

**Comment by lasselindqvist** [comment]
Hi. The Proguard is run in a forked JVM (https://github.com/wvengen/proguard-maven-plugin/blob/154987ae84a84bf580b50f06ee9a273a64bc18a2/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L953) and all general JVM arguments are not passed on (https://github.com/wvengen/proguard-maven-plugin/blob/154987ae84a84bf580b50f06ee9a273a64bc18a2/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L961). Should be relatively easy to include propagating this parameter by reading it with System.getProperty and passing it on.
