### ISSUE TITLE
Deploy 2.3.2-SNAPSHOT to maven central

### ISSUE THREAD

**Issue by jhordies** [wvengen/proguard-maven-plugin#135]
Could you deploy the 2.3.2-SNAPSHOT on maven central ?
I'm probably not the only one having a broken pipeline because of this missing dependency (proguard-base:7.0.0). 
Thanks

**Comment by lasselindqvist** [comment]
I hope to release it as a real release by the end of this week.

**Comment by jhordies** [comment]
That would be nice, ATM I can't deploy the bug fix of my application.

**Comment by lasselindqvist** [comment]
Meanwhile it should be available here https://oss.sonatype.org/content/repositories/snapshots/com/github/wvengen/proguard-maven-plugin/2.3.2-SNAPSHOT/

**Comment by aseyfpour** [comment]
Any update on this topic?

When next version will be available on the maven repository?

**Comment by lasselindqvist** [comment]
Release fails now due to https://issues.sonatype.org/browse/OSSRH-66257?jql=text%20~%20%22java%2016%22
but I will have to downgrade Java to release or get the workaround working.

**Comment by lasselindqvist** [comment]
2.4.0 is now in Maven Central
https://repo1.maven.org/maven2/com/github/wvengen/proguard-maven-plugin/2.4.0/
