### ISSUE TITLE
Release 2.5.0 and 2.5.1 are not tagged and do not have GitHub release

### ISSUE THREAD

**Issue by Marcono1234** [wvengen/proguard-maven-plugin#163]
Hello,
it appears release 2.5.0 and 2.5.1 neither have Git tags nor do they have GitHub release entries.
Could you please add the Git tags and create the corresponding GitHub releases?

**Comment by lasselindqvist** [comment]
I will do that manually at some point. Is the need in your case for JitPack or something else?

**Comment by Marcono1234** [comment]
No, I just wanted to use GitHub's feature to compare changes between releases and noticed that the releases are missing. It appears Dependabot also has its issues with this because it cannot show the changes either.

So it would be nice to have the commits tagged, but it is not blocking me in any way at the moment.

**Comment by s17t** [comment]
This is not blocking but the new versions are not advertised: the website and the github project still show 2.4.0

**Comment by lasselindqvist** [comment]
https://github.com/wvengen/proguard-maven-plugin/releases/tag/proguard-maven-plugin-2.5.1

2.5.1 released. 2.5.0 I will not release since it had quite a breaking bug.

**Comment by lasselindqvist** [comment]
Also updated the site now.

**Comment by Marcono1234** [comment]
Thanks! I (or you) can close this issue now, right?
