### ISSUE TITLE
Constructor converted into <init>

### ISSUE THREAD

**Issue by ypkkhatri** [wvengen/proguard-maven-plugin#208]
I have recently started looking into this plugin, but I see some of the classes constructor are missing from the class and in the map file it says:
```
void <init>(...) -> <init>
```
Where three dots are the constructor arguments.

For example:
```java
class MyClass {
    public MyClass(String s) {}
}
```
Map files show:
```
MyClass -> a
   void <init>(String) -> <init>
```

Am I missing something, because it happening to a lot of classes?

**Comment by lasselindqvist** [comment]
The question is not really related to this plugin itself, so for more help, ask https://github.com/Guardsquare/proguard/issues
