### ISSUE TITLE
cannot get new version from maven

### ISSUE THREAD

**Issue by fabio1999ita** [wvengen/proguard-maven-plugin#209]
hello, i cannot get the new version of proguard from maven

![image](https://user-images.githubusercontent.com/27001568/159791187-73eb044f-d18d-4e03-a32a-f421292ca384.png)

**Comment by lasselindqvist** [comment]
It is there:
https://repo1.maven.org/maven2/com/github/wvengen/proguard-maven-plugin/2.5.3/proguard-maven-plugin-2.5.3.jar
https://repo1.maven.org/maven2/com/github/wvengen/proguard-maven-plugin/2.5.3/proguard-maven-plugin-2.5.3.pom

I don't think I can help much here. Maybe your local Maven cache such as Artifactory has the problem, maybe a cached failure to retrieve in Maven. You can try asking in the mailing lists for Maven: https://maven.apache.org/mailing-lists.html
