### ISSUE TITLE
 the  generated   jar could not be scanned by class loader 

### ISSUE THREAD

**Issue by Jaware** [wvengen/proguard-maven-plugin#22]
i tried to use this proguard plugin ，the generated  jar is  almost the same to the original jar after  decompilation,  however the classes in  jar could not be scanned by class loader ，i use spring,the sourse code is PathMatchingResourcePatternResolver.java---getClassLoader().getResources("org/demo/config/").
the getResourses method return  no jar囧,while when i replace it to the original jar it returned the jar, so strange........can anyone help me...

**Comment by fmarot** [comment]
I faced the exact same problem today and the following code was not working after proguard created the jar:

provider = new ClassPathScanningCandidateComponentProvider(false)
provider.addIncludeFilter(new AssignableTypeFilter(interfaceClass));
provider.findCandidateComponents("com.mypackage"); // returns nothing after proguard !

What was astonishing was that by unziping and recreating the jar with zip, it worked ! In the end, you just have to add the following option in Proguard config: -keepdirectories (without parameters).

Hope it may help somebody as we lost a lot of time on this problem ;)
