### ISSUE TITLE
Search for proguardInclude on plugin classpath

### ISSUE THREAD

**Issue by sewe** [wvengen/proguard-maven-plugin#24]
Other Maven plugins like the maven-checkstyle-plugin offer the option to place the configuration file on the plugin’s classpath, thus making it easy to share the configuration among multiple projects (you can deploy your configuration to a Maven repo and it will get resolved from there). See https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-checker-config.html.

It would be great if the proguard-maven-plugin would also offer this feature, in particular as ProGuard configurations can be quite lengthy and in need of inline comments.

If there is interest in this feature, I’d be willing to prepare a pull request.

**Comment by cmorty** [comment]
This project is in low maintenance mode. Thus if you send a PR I'll merge it and send an email to wvengen to make new release. :)

**Comment by wvengen** [comment]
I'll keep an eye on pull requests :)
