### ISSUE TITLE
<attach>true</attach> ignores <outjar/>

### ISSUE THREAD

**Issue by jinahya** [wvengen/proguard-maven-plugin#26]
Following configuration which doesn't have `<attach/>` works fine.
````
<injar>in.jar</injar>
<outjar>out.jar<outjar>
````
When I tried to add `<attach>true</attach>`,

````
<injar>in.jar</injar>
<outjar>out.jar<outjar>
<attach>true</attach>
````
`<outjar/>` ignored and `in-small.jar` is generated.

**Comment by jinahya** [comment]
I found the `<attachArtifactClassifier/>` is automatically applied when `attach` is `true'.

**Comment by cmorty** [comment]
I'll close it. If you think this is a bug, please feel free to fix it and send a pull-request.
