### ISSUE TITLE
Upgrade Proguard to 7.3.2

### ISSUE THREAD

**Issue by ebourg** [wvengen/proguard-maven-plugin#261]
Hi,

Could you please upgrade Proguard to at least 7.3.2, this is the first version supporting Java 20.

Thank you

**Comment by lasselindqvist** [comment]
I will happily merge any pull requests.

**Comment by lasselindqvist** [comment]
https://github.com/wvengen/proguard-maven-plugin/pull/263 and https://github.com/wvengen/proguard-maven-plugin/pull/259 will update the version. Are you able to test the functionality after merging, but before releasing to Maven Central?
