### ISSUE TITLE
Java 22 support?

### ISSUE THREAD

**Issue by lordarnoud** [wvengen/proguard-maven-plugin#326]
Sorry if these things are not supposed to be asked as an issue but I couldn't find any other option on where to ask this question. But is there any estimate on when the Java 22 support will be released on maven? :) And how long does it normally take to support a new version? Seeing how Java now releases way more often.

**Comment by lasselindqvist** [comment]
The plugin supports any Java version automatically. Just change the Proguard version in the configuration.
