### ISSUE TITLE
issue with compiling with proguard

### ISSUE THREAD

**Issue by jman13378** [wvengen/proguard-maven-plugin#343]
having an issue with compiling with proguard
<details><summary>Proguard Config</summary>
<p>

# Keep main method
-keep public class * {
    public static void main(java.lang.String[]);
}

# Keep the specific onEnable method
-keep class info.sokobot.crazygens.Main {
    public void onEnable();
}

# General ProGuard options
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontwarn
-ignorewarnings

# Include all dependency JARs as library jars
-libraryjars <java.home>/lib/rt.jar
-libraryjars <java.home>/lib/jce.jar

# Add your project dependencies here
-libraryjars lib/sqlite-jdbc-3.42.0.0.jar
-libraryjars lib/joda-time-2.12.5.jar
-libraryjars lib/triumph-gui-3.1.7.jar
-libraryjars lib/adventure-api-4.14.0.jar
-libraryjars lib/adventure-key-4.14.0.jar
-libraryjars lib/examination-api-1.3.0.jar
-libraryjars lib/examination-string-1.3.0.jar
-libraryjars lib/adventure-text-serializer-legacy-4.14.0.jar
-libraryjars lib/adventure-text-serializer-gson-4.14.0.jar
-libraryjars lib/adventure-text-serializer-json-4.14.0.jar
-libraryjars lib/adventure-platform-bukkit-4.3.2.jar
-libraryjars lib/adventure-platform-api-4.3.2.jar
-libraryjars lib/adventure-text-serializer-bungeecord-4.3.2.jar
-libraryjars lib/adventure-nbt-4.13.1.jar
-libraryjars lib/adventure-text-minimessage-4.15.0.jar
-libraryjars lib/annotations-19.0.0.jar
-libraryjars lib/gson-2.10.1.jar

</p>
</details> 

<details><summary>My pom.xml</summary>
<p>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>info.sokobot.crazygens</groupId>
	<artifactId>crazygens</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<repositories>
		<repository>
			<id>opencollab-snapshot</id>
			<url>https://repo.opencollab.dev/main/</url>
		</repository>
		<repository>
			<id>spigot-repo</id>
			<url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
		</repository>
		<repository>
			<id>jitpack-repo</id>
			<url>https://jitpack.io</url>
		</repository>
		<repository>
			<id>placeholderapi</id>
			<url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
		</repository>
	</repositories>
	<dependencies>

		<dependency>
			<groupId>org.xerial</groupId>
			<artifactId>sqlite-jdbc</artifactId>
			<version>3.42.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-nop</artifactId>
			<version>2.0.6</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>2.12.5</version>
		</dependency>
		<dependency>
			<groupId>dev.triumphteam</groupId>
			<artifactId>triumph-gui</artifactId>
			<version>3.1.7</version>
		</dependency>
		<dependency>
			<groupId>net.kyori</groupId>
			<artifactId>adventure-platform-bukkit</artifactId>
			<version>4.3.2</version>
		</dependency>
		<dependency>
			<groupId>net.kyori</groupId>
			<artifactId>adventure-text-minimessage</artifactId>
			<version>4.15.0</version>
		</dependency>
		<dependency>
			<groupId>me.clip</groupId>
			<artifactId>placeholderapi</artifactId>
			<version>2.11.2</version>
			<scope>provided</scope>
		</dependency>

    <dependency>
           <groupId>org.spigotmc</groupId>
           <artifactId>spigot-api</artifactId>
           <version>1.20.6-R0.1-SNAPSHOT</version>
           <scope>provided</scope>
    </dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.4</version>
				<configuration>

					<relocations>
						<relocation>
							<pattern>dev.triumphteam.gui</pattern>
							<shadedPattern>info.sokobot.crazygens</shadedPattern> 
						</relocation>
					</relocations>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>

			</plugin>
			<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<version>2.6.1</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>proguard</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<proguardClasspath>
						<path>${project.build.directory}/CrazyGens-${project.version}.jar</path>
					</proguardClasspath>
					<proguardConfig>${project.basedir}/proguard.pro</proguardConfig>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>

</p>
</details> 
<details><summary>Maven Errors</summary>
<p>

 [proguard] Warning: com.google.common.base.Preconditions: can't find superclass or interface java.lang.Object
 [proguard] Warning: com.google.common.collect.ImmutableList: can't find superclass or interface java.util.List
 [proguard] Warning: com.google.common.collect.ImmutableList: can't find superclass or interface java.util.RandomAccess
 [proguard] Warning: com.google.common.graph.MutableGraph: can't find superclass or interface java.lang.Object
 [proguard] Warning: me.clip.placeholderapi.PlaceholderAPI: can't find superclass or interface java.lang.Object
 [proguard] Warning: net.md_5.bungee.api.ChatColor: can't find superclass or interface java.lang.Object
 [proguard] Warning: net.md_5.bungee.api.ChatMessageType: can't find superclass or interface java.lang.Enum
 [proguard] Warning: net.md_5.bungee.api.chat.BaseComponent: can't find superclass or interface java.lang.Object
 [proguard] Warning: net.md_5.bungee.chat.ComponentSerializer: can't find superclass or interface java.lang.Object
 [proguard] Warning: net.md_5.bungee.chat.TranslationRegistry: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.Bukkit: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.Color: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.DyeColor: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.FireworkEffect: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.Location: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.Location: can't find superclass or interface java.lang.Cloneable
 [proguard] Warning: org.bukkit.Material: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.Nameable: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.NamespacedKey: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.OfflinePlayer: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.Server: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.SoundCategory: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.Tag: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.World: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.block.Block: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.block.banner.Pattern: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.block.banner.PatternType: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.boss.BarColor: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.boss.BarFlag: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.boss.BarStyle: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.boss.BossBar: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.command.CommandSender: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.command.CommandSender$Spigot: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.command.ConsoleCommandSender: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.command.ProxiedCommandSender: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.configuration.MemorySection: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.enchantments.Enchantment: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.entity.Damageable: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.entity.Entity: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.entity.HumanEntity: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.entity.LivingEntity: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.entity.Player: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.entity.Wither: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.event.Event: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.event.Event$Result: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.event.EventException: can't find superclass or interface java.lang.Exception
 [proguard] Warning: org.bukkit.event.EventHandler: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.event.EventHandler: can't find superclass or interface java.lang.annotation.Annotation
 [proguard] Warning: org.bukkit.event.EventPriority: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.event.HandlerList: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.event.Listener: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.event.inventory.InventoryAction: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.event.inventory.InventoryType: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.generator.WorldInfo: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.Inventory: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.Inventory: can't find superclass or interface java.lang.Iterable
 [proguard] Warning: org.bukkit.inventory.InventoryHolder: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.InventoryView: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.ItemFactory: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.ItemFlag: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.inventory.ItemStack: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.ItemStack: can't find superclass or interface java.lang.Cloneable
 [proguard] Warning: org.bukkit.inventory.PlayerInventory: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.BannerMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.BookMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.BookMeta$Generation: can't find superclass or interface java.lang.Enum
 [proguard] Warning: org.bukkit.inventory.meta.BookMeta$Spigot: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.FireworkEffectMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.FireworkMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.ItemMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.ItemMeta: can't find superclass or interface java.lang.Cloneable
 [proguard] Warning: org.bukkit.inventory.meta.LeatherArmorMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.MapMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.SkullMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.inventory.meta.WritableBookMeta: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.map.MapView: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.permissions.Permissible: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.persistence.PersistentDataContainer: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.persistence.PersistentDataHolder: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.persistence.PersistentDataType: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.plugin.EventExecutor: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.plugin.Plugin: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.plugin.PluginDescriptionFile: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.plugin.PluginManager: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.profile.PlayerProfile: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.profile.PlayerProfile: can't find superclass or interface java.lang.Cloneable
 [proguard] Warning: org.bukkit.profile.PlayerTextures: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.scheduler.BukkitScheduler: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.util.Vector: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.bukkit.util.Vector: can't find superclass or interface java.lang.Cloneable
 [proguard] Warning: org.checkerframework.checker.nullness.qual.NonNull: can't find superclass or interface java.lang.Object
 [proguard] Warning: org.checkerframework.checker.nullness.qual.NonNull: can't find superclass or interface java.lang.annotation.Annotation
 [proguard] Note: com.google.gson.internal.UnsafeAllocator: can't find dynamically referenced class sun.misc.Unsafe
 [proguard] Note: com.google.gson.internal.sql.SqlTypesSupport: can't find dynamically referenced class java.sql.Date
 [proguard] Note: info.sokobot.crazygens.components.util.VersionHelper: can't find dynamically referenced class com.destroystokyo.paper.PaperConfig
 [proguard] Note: net.kyori.adventure.platform.viaversion.ViaFacet: can't find dynamically referenced class com.viaversion.viaversion.api.ViaAPI
 [proguard] Note: com.google.gson.internal.ConstructorConstructor accesses a declared constructor '<init>()' dynamically
 [proguard] Note: com.google.gson.internal.ReflectionAccessFilterHelper$AccessChecker accesses a declared method 'canAccess(java.lang.Object)' dynamically
 [proguard] Note: com.google.gson.internal.UnsafeAllocator accesses a declared field 'theUnsafe' dynamically
 [proguard] Note: com.google.gson.internal.UnsafeAllocator accesses a method 'allocateInstance(java.lang.Class)' dynamically
 [proguard] Note: com.google.gson.internal.UnsafeAllocator accesses a declared method 'getConstructorId(java.lang.Class)' dynamically
 [proguard] Note: com.google.gson.internal.UnsafeAllocator accesses a declared method 'newInstance(java.lang.Class,int)' dynamically
 [proguard] Note: com.google.gson.internal.UnsafeAllocator accesses a declared method 'newInstance(java.lang.Class,java.lang.Class)' dynamically
 [proguard] Note: com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper accesses a method 'isRecord()' dynamically
 [proguard] Note: com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper accesses a method 'getRecordComponents()' dynamically
 [proguard] Note: com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper accesses a method 'getName()' dynamically
 [proguard] Note: com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper accesses a method 'getType()' dynamically
 [proguard] Note: info.sokobot.crazygens.builder.item.BaseItemBuilder accesses a declared field 'displayName' dynamically
 [proguard] Note: info.sokobot.crazygens.builder.item.BaseItemBuilder accesses a declared field 'lore' dynamically
 [proguard] Note: info.sokobot.crazygens.builder.item.ItemBuilder accesses a declared field 'profile' dynamically
 [proguard] Note: info.sokobot.crazygens.builder.item.SkullBuilder accesses a declared field 'profile' dynamically
 [proguard] Note: info.sokobot.crazygens.components.nbt.LegacyNbt accesses a method 'getString(java.lang.String)' dynamically
 [proguard] Note: info.sokobot.crazygens.components.nbt.LegacyNbt accesses a method 'remove(java.lang.String)' dynamically
 [proguard] Note: info.sokobot.crazygens.components.nbt.LegacyNbt accesses a method 'setString(java.lang.String,java.lang.String)' dynamically
 [proguard] Note: info.sokobot.crazygens.components.nbt.LegacyNbt accesses a method 'setBoolean(java.lang.String,boolean)' dynamically
 [proguard] Note: info.sokobot.crazygens.components.nbt.LegacyNbt accesses a method 'hasTag()' dynamically
 [proguard] Note: info.sokobot.crazygens.components.nbt.LegacyNbt accesses a method 'getTag()' dynamically
 [proguard] Note: info.sokobot.crazygens.components.nbt.LegacyNbt accesses a declared constructor '<init>()' dynamically
 [proguard] Note: info.sokobot.crazygens.components.nbt.LegacyNbt accesses a method 'asNMSCopy(org.bukkit.inventory.ItemStack)' dynamically
 [proguard] Note: net.kyori.adventure.platform.bukkit.CraftBukkitFacet accesses a method 'getHandle()' dynamically
 [proguard] Note: net.kyori.adventure.platform.bukkit.CraftBukkitFacet$Book1_13 accesses a constructor '<init>(java.lang.String)' dynamically
 [proguard] Note: net.kyori.adventure.platform.bukkit.PaperFacet accesses a declared method 'deserialize(java.lang.String)' dynamically
 [proguard] Note: net.kyori.adventure.platform.viaversion.ViaFacet accesses a declared method 'majorVersion()' dynamically
 [proguard] Note: org.joda.time.DateTimeUtils accesses a method 'getInstance(java.util.Locale)' dynamically
 [proguard] Note: org.joda.time.DateTimeZone accesses a constructor '<init>()' dynamically
 [proguard] Note: org.joda.time.DateTimeZone accesses a constructor '<init>()' dynamically
 [proguard] Warning: library class net.md_5.bungee.chat.ComponentSerializer depends on program class com.google.gson.JsonElement
 [proguard] Warning: library class net.md_5.bungee.chat.ComponentSerializer depends on program class com.google.gson.JsonElement
 [proguard] Warning: library class net.md_5.bungee.chat.ComponentSerializer depends on program class com.google.gson.JsonElement
 [proguard] Warning: library class net.md_5.bungee.chat.ComponentSerializer depends on program class com.google.gson.JsonElement
 [proguard] Warning: library class net.md_5.bungee.chat.ComponentSerializer depends on program class com.google.gson.JsonElement
 [proguard] Warning: library class net.md_5.bungee.chat.ComponentSerializer depends on program class com.google.gson.JsonDeserializationContext
 [proguard] Warning: library class net.md_5.bungee.chat.ComponentSerializer depends on program class com.google.gson.JsonElement
 [proguard] Warning: library class net.md_5.bungee.chat.ComponentSerializer depends on program class com.google.gson.JsonDeserializationContext
 [proguard] Warning: there were 48807 unresolved references to classes or interfaces.
 [proguard]          You may need to add missing library jars or update their versions.
 [proguard]          If your code works fine without the missing classes, you can suppress
 [proguard]          the warnings with '-dontwarn' options.
 [proguard]          (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedclass)
 [proguard] Warning: there were 43 instances of library classes depending on program classes.
 [proguard]          You must avoid such dependencies, since the program classes will
 [proguard]          be processed, while the library classes will remain unchanged.
 [proguard]          (https://www.guardsquare.com/proguard/manual/troubleshooting#dependency)
 [proguard] Warning: there were 80 unresolved references to program class members.
 [proguard]          Your input classes appear to be inconsistent.
 [proguard]          You may need to recompile the code.
 [proguard]          (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedprogramclassmember)
 [proguard] Warning: there were 3 unresolved references to library class members.
 [proguard]          You probably need to update the library versions.
 [proguard]          (https://www.guardsquare.com/proguard/manual/troubleshooting#unresolvedlibraryclassmember)
 [proguard] Unexpected error
 [proguard] java.io.IOException: Please correct the above warnings first.
 [proguard] 	at proguard.Initializer.execute(Initializer.java:526) ~[proguard-base-7.4.1.jar:7.4.1]
 [proguard] 	at proguard.pass.PassRunner.run(PassRunner.java:24) ~[proguard-base-7.4.1.jar:7.4.1]
 [proguard] 	at proguard.ProGuard.initialize(ProGuard.java:353) ~[proguard-base-7.4.1.jar:7.4.1]
 [proguard] 	at proguard.ProGuard.execute(ProGuard.java:142) ~[proguard-base-7.4.1.jar:7.4.1]
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:648) ~[proguard-base-7.4.1.jar:7.4.1]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.050 s
[INFO] Finished at: 2024-06-11T22:44:25-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.6.1:proguard (default) on project crazygens: Obfuscation failed (result=1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

</p>
</details>

**Comment by lasselindqvist** [comment]
If you use one of the newer Javas, it no longer has
```
-libraryjars <java.home>/lib/rt.jar
-libraryjars <java.home>/lib/jce.jar
```
Check your Java installation and see which actual files to use.
