### ISSUE TITLE
Please update java version, proguard-base and proguard-core

### ISSUE THREAD

**Issue by valimaties** [wvengen/proguard-maven-plugin#379]
Hi.
Please, update to java version at least 22. Now java version 24 is already available. I have my project build in LibericaSDK 22, so I cannot use the plugin.
Also, the latest version for proguard base is now 7.6.0, and proguard-core is 9.1.6

Thanks

**Comment by valimaties** [comment]
I see that it is already a PR with no #373 . How can be merged this one?

**Comment by lasselindqvist** [comment]
Maybe you meant Java 23, not 24.

But also note that you can always set the version yourself. What we have here is just the default version.

**Comment by lasselindqvist** [comment]
Try the last example on page https://wvengen.github.io/proguard-maven-plugin/

**Comment by valimaties** [comment]
Ohh... I've see...
In configuration I need to change proguardVersion to use 7.6.0 , and in dependencies I need to add those two dependencies, of proguard-base and proguard-core.

Thank you very much. ❤️
