### ISSUE TITLE
Support wildcard artefactId inclusion/exclusion

### ISSUE THREAD

**Issue by mahileeb** [wvengen/proguard-maven-plugin#4]
It would be great if you could include/exclude using a wildcard artefactId e.g.

```
<exclusion>
    <groupId>com.x</groupId>
    <artefactId>*</groupId>
</exclusion>
```

or take the fact that artefactId is null to mean include/exclude all

**Comment by bookhuntress** [comment]
Hi,

Mahileeb's suggestion is something that I currently need at work. Would like to know if this has been implemented and released? (I could not understand what was being talked about #5). If this feature was already released, may I know which version?

Also, may I know the requirements for becoming co-maintainer/co-developer?

Thanks.

**Comment by cmorty** [comment]
The log shows what is released when:
https://github.com/wvengen/proguard-maven-plugin/commits/master

And to become a co-developer you just need to make a pull-request.

**Comment by wvengen** [comment]
Looking at #14, wildcards are indeed supported, though we seem to be missing some documentation. You can look at [ArtifactFilterTest.java](https://github.com/wvengen/proguard-maven-plugin/blob/master/src/test/java/com/github/wvengen/maven/proguard/ArtifactFilterTest.java) to see what wildcards are supported.
