### ISSUE TITLE
Obfuscation failed 

### ISSUE THREAD

**Issue by taar1** [wvengen/proguard-maven-plugin#42]
I'm getting the error "Obfuscation failed" when trying to do "mvn clean install" with Proguard 2.0.11.

My pom.xml looks like this:

<dependencies>
    <dependency>
            <groupId>com.github.wvengen</groupId>
            <artifactId>proguard-maven-plugin</artifactId>
            <version>2.0.11</version>
    </dependency>
</dependencies>

...

```
        <plugin>
            <groupId>com.github.wvengen</groupId>
            <artifactId>proguard-maven-plugin</artifactId>
            <executions>
                <execution>
                    <phase>process-classes</phase>
                    <goals>
                        <goal>proguard</goal>
                    </goals>
                    <configuration>
                        <proguardVersion>5.0</proguardVersion>
                        <maxMemory>512m</maxMemory>
                        <injar>android-classes</injar>
                        <options>
                            <option>-allowaccessmodification</option>
                            <option>-keep public class * extends java.applet.Applet { *; }</option>
                        </options>
                        <libs>
                            <lib>${env.JAVA_HOME}/jre/lib/rt.jar</lib>
                            <lib>${env.JAVA_HOME}/jre/lib/jsse.jar</lib>
                        </libs>
                        <skip>false</skip>
                        <obfuscate>false</obfuscate>
                        <addMavenDescriptor>false</addMavenDescriptor>
                    </configuration>
                </execution>
            </executions>
        </plugin>
```

When I do MVN CLEAN INSTSALL I get this error:

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.0.11:proguard (default) on project marlin-app-android: Obfuscation failed (result=1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

Thanks for any help.

**Comment by cmorty** [comment]
@taar1 Pull requests are welcome. ;) Currently neither me nor wvengen are using this plugin and are keeping this alive in low-maintenance mode.

**Comment by FibreFoX** [comment]
@taar1 can you create some simple project to recreate that issue? (maybe some dummy-repository on github where I can checkout and confirm that issue)
