### ISSUE TITLE
springboot and proguard-maven-plugin

### ISSUE THREAD

**Issue by hanasian** [wvengen/proguard-maven-plugin#48]
Hi!
I have developed a platform with springboot.I want to prevent others to decompile java source code.
How I make use of the plugin to confuse the java source code.
Please give me some suggestions about confusing source code.

**Comment by wvengen** [comment]
Hi, if you need more info on using proguard, please see http://proguard.sourceforge.net/
This plugin merely integrates it with maven.

**Comment by Amithpn** [comment]
Hi! Please give me the skeleton plugin which can work for Spring boot project with embedded tomcat. It complains me of missing classes when i run it with progaurd plugin. Please do needful

**Comment by cmorty** [comment]
Please see @wvengen's comment. Your issue is with proguard, not this plugin.

**Comment by Amithpn** [comment]
Hi! can someone give me some working plugin for spring boot app?
