### ISSUE TITLE
Creating temporary library JAR directory fails if it already exists

### ISSUE THREAD

**Issue by snooper77** [wvengen/proguard-maven-plugin#49]
Hi,

I'm using the plugin with the

  `<putLibraryJarsInTempDir>true</putLibraryJarsInTempDir>`

option because of a large classpath. When running mvn proguard:proguard and when *not* having run mvn clean beforehand the temporary library directory ('tempLibraryjars') may already exist. If that's the case then the following call to mkdir() will return false and the proguard plugin will throw an exception:

https://github.com/wvengen/proguard-maven-plugin/blob/master/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L580

Can you please ignore the return value of mkdir() and instead check for the existence of the directory after the call to mkdir(), followed by cleaning it?

Thanks.

**Comment by FibreFoX** [comment]
Hi @snooper77 , this project is on "low maintainance"-mode, so creating a working pull-request works faster than just opening new issues :smile:

**Comment by snooper77** [comment]
Thanks, but I can't do it from my work place and I don't have maven/git set up at home. The change is trivial and looks like this:

Replace [lines 580-582 in `ProGuardMojo`](https://github.com/wvengen/proguard-maven-plugin/blob/master/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L580):
```
			if (!tempLibraryjarsDir.mkdir()) {
				throw new MojoFailureException("Can't create temporary libraryJars directory: " + tempLibraryjarsDir.getAbsolutePath());
			}

```

by:

```
			tempLibraryjarsDir.mkdir();
			if (!tempLibraryjarsDir.exists()) {
				throw new MojoFailureException("Can't create temporary libraryJars directory: " + tempLibraryjarsDir.getAbsolutePath());
			}

```

**Comment by wvengen** [comment]
Sounds like a useful change, thanks.

**Comment by snooper77** [comment]
Just wondering if it's an issue if the temp library directory isn't purged between runs? If it's an issue then it should be cleaned prior to using it.

**Comment by FibreFoX** [comment]
Cleaning that folder (as it is temporary), sounds like a wonderful idea, especially for reducing false-positives. That would imitate current behaviour more equal than reusing existing one.

@wvengen do you work on this? Just want to reduce double-work ;) and would create a PR about this, when nobody else is working on it.

**Comment by wvengen** [comment]
Nope, PR welcome! :)

**Comment by FibreFoX** [comment]
https://github.com/FibreFoX/proguard-maven-plugin/commit/9df7725b1141475bc21e32291d9ced8e42b3c76a

Will make another commit for deleting the contents first :) there should be some PR tomorrow

**Comment by FibreFoX** [comment]
Pull-Request is available ;)
