### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by brcolow** [wvengen/proguard-maven-plugin#51]
Hello @wvengen - would you be willing to do a new release? This would allow for me to use the new `<proguardJar>` feature and not have to use a `SNAPSHOT` version, which in turn would allow for me to add back the `requirePluginVersions` rule to `maven-enforcer-plugin`!

Let me know what you think, and thanks!

**Comment by wvengen** [comment]
Hi! I'd be happy to do so, but the last commits are already released in version 2.0.13. Or did I miss something?

**Comment by brcolow** [comment]
Ah, you are totally correct. I was only looking at the releases page on Github -_-. Sorry for the noise!
