### ISSUE TITLE
Logical issue for attachment of ProGuard map and seed files as artifacts

### ISSUE THREAD

**Issue by Syquel** [wvengen/proguard-maven-plugin#55]
The attachment of ProGuard map and seed files as artifacts is not possible if the injar filename is the same as the outjar filename.

The attachment feature was introduced by #36 , but did not consider this case.

**Comment by FibreFoX** [comment]
Thanks for catching this 👍

**Comment by FibreFoX** [comment]
Re-opened, as this is not yet released

**Comment by wvengen** [comment]
Just released 2.0.14, should appear in Maven Central today.

**Comment by FibreFoX** [comment]
@wvengen this was fast, thanks a lot :)
