### ISSUE TITLE
How to instal this

### ISSUE THREAD

**Issue by fafayqa** [wvengen/proguard-maven-plugin#58]
Guys, it would be really helpful if you would tell us less experienced NetBeans users how to install this ProGuard Maven plugin into NetBeans (step-by-step would be great!)...thanx in advance (as this way it is quite useless or just for JAVA gurus, sorry))

**Comment by FibreFoX** [comment]
Quoting the README.md:
> For usage, please read the generated Documentation.

http://wvengen.github.io/proguard-maven-plugin/

This is no NetBeans-question, this is some Maven-question.

All in all you have to add this plugin to your plugins-section of your pom.xml, how to configure proguard is out of scope of this issue (don't kill the messenger xD). If you want to use JavaFX, you might want to take a look at this project: https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/it/08-build-with-proguard/pom.xml (yes, I know, shameless advertizing, but it is a valid project-configuration utilizing the proguard-maven-plugin)

**Comment by FibreFoX** [comment]
@fafayqa Do you need further feedback? I would like to close this issue then.
