### ISSUE TITLE
Fail to parse  <![CDATA[<init>]]>

### ISSUE THREAD

**Issue by Sharcoux** [wvengen/proguard-maven-plugin#59]
The following code is not parsed correctly:

```
<option>-keepclassmembers class * implements JsonSerializable {
    <![CDATA[<init>]]>;
}</option>
```

Log:
```
The ' characters around the executable and arguments are
not part of the command.
 [proguard] proguard.ParseException: Expecting class member name before ';' in argument number 132
 [proguard] 	at proguard.ConfigurationParser.checkJavaIdentifier(ConfigurationParser.java:1260)
 [proguard] 	at proguard.ConfigurationParser.parseMemberSpecificationArguments(ConfigurationParser.java:921)
 [proguard] 	at proguard.ConfigurationParser.parseClassSpecificationArguments(ConfigurationParser.java:748)
 [proguard] 	at proguard.ConfigurationParser.parseKeepClassSpecificationArguments(ConfigurationParser.java:534)
 [proguard] 	at proguard.ConfigurationParser.parse(ConfigurationParser.java:165)
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:530)
```

It works fine with <fields> and <methods> though...

[Reference](https://www.guardsquare.com/en/proguard/manual/usage )

**Comment by FibreFoX** [comment]
Have you tried to remove the linebreaks?

```xml
<option>-keepclassmembers class * implements JsonSerializable {    <![CDATA[<init>]]>;}</option>
```

**Comment by Sharcoux** [comment]
Just did. Same reasult (which I consider a good news as parsing xml should not depend on line breaks).

**Comment by FibreFoX** [comment]
Hm, that was my first stupid guess ;)

Do you have a project where this can be reproduced?

**Comment by Sharcoux** [comment]
Hum, not right here cause I use it in a huge confidential project, but I might create one I guess, although I am quite sure that any project will do.

**Comment by FibreFoX** [comment]
No problem, take your time. As I'm not that into proguard-knowhow, a small project where I can reproduce this quickly helps a lot. Sometimes it's the special project setup.

**Comment by Sharcoux** [comment]
Ok. I have a dummy HelloWorld project. Where should I put it ?

**Comment by FibreFoX** [comment]
Attach to this ticket, or just create a small public github-project.

**Comment by Sharcoux** [comment]
[issue.zip](https://github.com/wvengen/proguard-maven-plugin/files/1236185/issue.zip)

**Comment by FibreFoX** [comment]
There is a problem with your configuration, I'm quoting the ProGuard manual:
```
[@annotationtype] [[!]public|final|abstract|@ ...] [!]interface|class|enum classname
    [extends|implements [@annotationtype] classname]
[{
    [@annotationtype] [[!]public|private|protected|static|volatile|transient ...] <fields> |
                                                                      (fieldtype fieldname);
    [@annotationtype] [[!]public|private|protected|static|synchronized|native|abstract|strictfp ...] <methods> |
                                                                                           <init>(argumenttype,...) |
                                                                                           classname(argumenttype,...) |
                                                                                           (returntype methodname(argumenttype,...));
    [@annotationtype] [[!]public|private|protected|static ... ] *;
    ...
}]
```

Please take a close look at the `init`-stuff: `<init>(argumenttype,...) |` this means you will have to include the signature of `<init>`.

Can you try with this configuration ( I also moved CDATA around as a wrapper)?
```xml
<option><![CDATA[-keepclassmembers class issue.Main {
    <fields>;
    <methods>;
    <init>(java.lang.String[]);
}]]></option>
```

**Comment by Sharcoux** [comment]
Oh... My bad I guess. On the page I linked as reference in my first post, you can read:

```
The specifications can also contain the following catch-all wildcards:
<init> | matches any constructor.
<fields> | matches any field.
<methods> | matches any method.
```

So I imagined I could just use <init> to keep all constructors...

**Comment by FibreFoX** [comment]
Don't know, if my suggestion is correct at all ;) as said, I'm not so good with ProGuard, but it worked for me.

**Comment by Sharcoux** [comment]
Hum, ok, at least it removes the error. I think that the correct syntax to match any constructor should be `<init>(...)`. But I didn't succeed to make it work, although I'm not sure if my test case is correct:

[issue.zip](https://github.com/wvengen/proguard-maven-plugin/files/1236254/issue.zip)

The class `NewClass` should be obfuscated and is totally not, so I can't check the effect of your solution... I'll get back into this later, unless you get what happens.

Thanks anyway.
