### ISSUE TITLE
Not able to provide/Change Obfuscated jar file name 

### ISSUE THREAD

**Issue by RakeshKoplodR** [wvengen/proguard-maven-plugin#60]
Hello @wvengen 

I am able to obfuscate my java application. But I am not able to change the output jar file name. It comming by default "filename-small.jar". I want to change the outjar file name. I tried by providing the name in -outjars but it is not reflected and it is still appended by -small.

**Comment by FibreFoX** [comment]
HI @RakeshKoplodR can you provide some project for us, to check this?

**Comment by lasselindqvist** [comment]
The "outjar" parameter actually implements what you want to have (https://github.com/wvengen/proguard-maven-plugin/blob/master/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L196)
I have myself used that functionality successfully, so I am closing this issue, but please reopen this if you are able to provide an example project that doesn't work.
