### ISSUE TITLE
Upgrade to ProGuard 6

### ISSUE THREAD

**Issue by wvengen** [wvengen/proguard-maven-plugin#64]
Message through mail:
> Are you planning to roll the plugin over to use Proguard 6?
> Currently the log tells me:  [proguard] ProGuard, version 5.2.1

**Comment by wvengen** [comment]
And later today:
> I renamed the Proguard installation in my .m2 to use the Proguard 6 jar instead. This works fine.
> However, I did get the following issue:  Java 9 attempts to use StringConcatFactory:
> I added -dontwarn java.lang.invoke.StringConcatFactory to my Proguard Conf file, and my game now runs fine.
> I also had to access some stubbed files from a JDK 8 installation:
> ```
> <proguardInclude>${basedir}/proguard.conf</proguardInclude>
>   <libs>
>     <lib>C:/Program Files/Java/jdk1.8.0_144/jre/lib/rt.jar</lib>
>     <lib>C:/Program Files/Java/jdk1.8.0_144/jre/lib/jsse.jar</lib>
>     <lib>C:/Program Files/Java/jdk1.8.0_144/jre/lib/ext/jfxrt.jar</lib>
>     (etc)
>   </libs>

**Comment by wvengen** [comment]
It seems this could break something.

**Comment by wvengen** [comment]
> I expect you've long known this, but just to let you know: you're plugin is working fine with Java 9. The trick was all in the proguard.conf file - in Java 9, this has obviously changed a lot: I got this working using proguard via the GUI. Then all issues were solved for me.

**Comment by fdrueke** [comment]
I get the following error with the current release 2.0.14 which still uses proguard 5.2.1:

> Can't process class [someclass.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8)) 

Changing the proguard-maven-plugin dependency to proguard 6.0.3 fixes this.
Thus I'd like to see this updated in the upcoming 2.0.15 release.

**Comment by fdrueke** [comment]
Are there any plans to upgrade to proguard 6 ?
At some point this needs to be done anyway, doesn't it?

FYI: 
since a few months we are using a locally modified plugin version that utilizes proguard 6.
No problems so far.

**Comment by cmorty** [comment]
@fdrueke Could you please create a pull-request. All maintainers are note really using this plugin anymore and are maintaining it for completely altruistic reasons. -> Thus there will be no proguard 6 unless you or someone else takes care of it. :)

**Comment by fdrueke** [comment]
Done

**Comment by simlu** [comment]
Can we get this merged in and released please?

**Comment by simlu** [comment]
Workaround for now is to specify proguard version as plugin dependency and then specify the proguard version as documented for this plugin.

**Comment by r0bnewt0n** [comment]
An example of using @simlu 's workaround:
```
      <plugin>
        <groupId>com.github.wvengen</groupId>
        <artifactId>proguard-maven-plugin</artifactId>
        <version>2.0.14</version>
        <dependencies>
          <dependency>
            <groupId>net.sf.proguard</groupId>
            <artifactId>proguard-base</artifactId>
            <version>6.1.0beta2</version>
          </dependency>
        </dependencies>
```

**Comment by lasselindqvist** [comment]
Proguard 6.1.0 was just released: https://sourceforge.net/p/proguard/discussion/182455/thread/8718d2cea2/
It would probably make sense to upgrade to this and bump the version to 2.1.0.

**Comment by lasselindqvist** [comment]
Bumped the version first to 6.0.3 via https://github.com/wvengen/proguard-maven-plugin/pull/78. The version is anyway configurable in the plugin, but for now 6.0.3 is a bit safer option than 6.1.0.

**Comment by lasselindqvist** [comment]
6.1.1 has now been available for a bit more than a year.
Bugs (https://sourceforge.net/p/proguard/bugs/) don't list anything new and high priority, so it should be safe to bump the default version to 6.1.1 in this issue.
