### ISSUE TITLE
Assembly inclusions list generic

### ISSUE THREAD

**Issue by Chuckame** [wvengen/proguard-maven-plugin#65]
Hi.
I'm working with this plugin, but there is an embarrassing case in auto-completion (in my case, on eclipse).
In Assembly class, there is an inclusions list that is no typed.
This imply auto-completion not working because of raw type.

Anyway, in code, inclusions list is getted as an `List<Inclusion>` line 647-648 : https://github.com/wvengen/proguard-maven-plugin/blob/f0ec275312f039978fa0f46f3d2b497f66ad4101/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L646
https://github.com/wvengen/proguard-maven-plugin/blob/f0ec275312f039978fa0f46f3d2b497f66ad4101/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L647

Can you just change `List inclusions` to `List<Inclusion> inclusions` in Assembly class ?
https://github.com/wvengen/proguard-maven-plugin/blob/f0ec275312f039978fa0f46f3d2b497f66ad4101/src/main/java/com/github/wvengen/maven/proguard/Assembly.java#L27

**Comment by lasselindqvist** [comment]
Closed via https://github.com/wvengen/proguard-maven-plugin/pull/66
