### ISSUE TITLE
exclude .class file inside jar file

### ISSUE THREAD

**Issue by akshay-1993** [wvengen/proguard-maven-plugin#69]
How can we exclude a .class file from the jar file.
The need of jar file is there but only the class should be excluded from it.

Windows 10
proguard version: 5.2.1
Java: 8

**Comment by FibreFoX** [comment]
How is this related to this maven-plugin? just set some filter while compiling your jar-file?!

**Comment by yannicklamprecht** [comment]
Do you want to exclude classes from being obfuscated?

**Comment by akshay-1993** [comment]
Yes, I do

**Comment by yannicklamprecht** [comment]
Here is an example of a pom.xml that is defining some options.
https://github.com/NickAcPT/Lithium-Spigot/blob/master/pom.xml

**Comment by lasselindqvist** [comment]
Closing as the linked example and the Proguard manual keep section (https://www.guardsquare.com/en/products/proguard/manual/usage#keepoptions) are enough to solve this and no actions here are necessary.
