### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by wvengen** [wvengen/proguard-maven-plugin#79]
Hi everyone, as you can see in the issues, my response is really slow. I'm sorry for the delay and extra work that has caused. It's due time to find one or more other people who'd be willing to maintain the project. That means mostly reviewing contributions, testing, keeping an eye on documentation and code quality; but most importantly, doing releases.

If anyone is interested, please respond here. I'm open to add people to this repository, or move the repository it to a new GH organisation if desired (don't forget to update doc generation config for the latter).

**Comment by lasselindqvist** [comment]
I can help with this, since I anyway have a need for this plugin.

**Comment by lasselindqvist** [comment]
Closing this now, but all contributions are still welcome of course, there are a few issues labeled with "good first issue" even for people new to this plugin.
