### ISSUE TITLE
Add an example for wildcard functionality to site

### ISSUE THREAD

**Issue by lasselindqvist** [wvengen/proguard-maven-plugin#88]
Add an example for wildcard functionality to site.
Relates to this PR https://github.com/wvengen/proguard-maven-plugin/pull/68
Ready docs can be found here: https://github.com/cjgriscom/proguard-maven-plugin/tree/feature/full-wildcard-support

**Comment by cjgriscom** [comment]
I created PR
https://github.com/wvengen/proguard-maven-plugin/pull/89

**Comment by lasselindqvist** [comment]
Fixed in https://github.com/wvengen/proguard-maven-plugin/pull/89
