### ISSUE TITLE
properties file can't be load

### ISSUE THREAD

**Issue by wxzmmm** [wvengen/proguard-maven-plugin#90]
I can't load properties file when I use proguard. I found the folder hasn't modify time when I open this jar use RAR. I unzipped the jar , then zip the jar, this issue has been resolved. 
![image](https://user-images.githubusercontent.com/8630949/59272270-3c806880-8c88-11e9-93af-ce8219bc68aa.png)

**Comment by lasselindqvist** [comment]
@wxzmmm can you explain a bit more why you think this is an issue with this plugin and not Proguard itself or something else? Proguard discussion is located in SourceForge https://sourceforge.net/p/proguard/discussion/182456/

**Comment by wxzmmm** [comment]
@lasselindqvist Thank you. You are right. This is really a issue with Proguard. Because I use Proguard without this plugin, this issue still exists.

**Comment by lasselindqvist** [comment]
Thanks. I will close this issue.

**Comment by wxzmmm** [comment]
@lasselindqvist This issue has been resolved. I add -keepdirectories to option.
