### ISSUE TITLE
Access denied when putLibraryJarsInTempDir = true

### ISSUE THREAD

**Issue by maokejackson** [wvengen/proguard-maven-plugin#92]
Hi, I have a multi modules project like this.

```
<project-root>
+- <module-1>
+- <module-2>
+- <module-3>  // proguard configured here
```

`<module-1>` and `<module-2>` are shaded together with `<module-3>` then only proceed to obfuscation.

It is working fine in version 2.0.14. When I update proguard-maven-plugin to version 2.1.0 without modifying configuration and run `mvn package`, it shows following error:

```
Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.1.0:proguard (default) on project my-project: Can't copy to temporary libraryJars directory: <project-root>\<module-1>\target\classes (Access is denied)
```

However, I can run it successfully if `<putLibraryJarsInTempDir>true</putLibraryJarsInTempDir>` is removed. Is there extra configuration needed in version 2.1.0 in order to put library jars in temporary directory?

**Comment by lasselindqvist** [comment]
https://github.com/wvengen/proguard-maven-plugin/blob/proguard-maven-plugin-2.1.0/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L604
creates the temporary directory, while the return value is not checked, the existence of the directory is checked anyway and that passes. 

We can also see that in 2.0.14
https://github.com/wvengen/proguard-maven-plugin/blob/proguard-maven-plugin-2.0.14/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L587
the code is the same.

What has changed is the used Java version from 1.5 to 1.6, but not sure how that could affect this. I have experienced these "Access is denied" problems in some other Maven builds as well, when trying to copy files to target directory. If this happens to other people, we could try upping the Java version to 1.7 and using https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempDirectory(java.lang.String,%20java.nio.file.attribute.FileAttribute...) to create a proper temporary folder. The current temp folder isn't deleted if the execution of the plugin fails at some point.

**Comment by maokejackson** [comment]
In version 2.0.14, I can see the library jars temporary directory created at `<project-root>\<module-3>\target\tempLibraryjars`.

In version 2.1.0, according to the error message, the temporary directory points to `<project-root>\<module-1>\target\classes`.

**Comment by lasselindqvist** [comment]
The expression is the same in both versions:
@parameter expression="${project.build.directory}/tempLibraryjars"
and that resolves to ${project.basedir}/target by default
so it seems like either ${project.build.directory} or ${project.basedir} is being overridden by something.

**Comment by maokejackson** [comment]
I create a simple project with following structure at https://github.com/maokejackson/test-proguard.

```
<project-root>
+- <module-1>
+- <module-2>
+- <module-3>  // proguard configured here
```

Below listed <module-3> configuration I have tested and the result:

* With proguard-maven-plugin version 2.1.0
    * <module-3> depends on <module-1> and <module-2>, failure.
    * <module-3> depends on <module-1>, failure.
    * <module-3> depends on <module-2>, failure.
    * <module-3> has no dependency, success.
    * <module-3> depends on commons-io:commons-io, success.
    * <module-3> depends on commons-io:commons-io and <module-1>, failure.
* With proguard-maven-plugin version 2.0.14
    * Same cases in version 2.1.0 all success.

It seems that error only happens when the module depends on other modules in the same project.

**Comment by lasselindqvist** [comment]
Thanks for the test project. Found the cause:
https://github.com/wvengen/proguard-maven-plugin/blob/proguard-maven-plugin-2.1.0/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L929

After https://github.com/wvengen/proguard-maven-plugin/commit/38f89eca43c4544a4a88a9527d0d5e435bea16d6
we now find the project in method getClasspathElement and what is returned is a directory and not a JAR file. This breaks in the file copying later. Removing that fixes the thing, but before removing that I will have to check if "injars" or "libraryjars" parameters accept directories in Proguard. If that is the case we need to handle the method differently for this case.

**Comment by lasselindqvist** [comment]
https://github.com/wvengen/proguard-maven-plugin/pull/93 fixes the issue for the example project. Can you confirm if that works for the real project, too?

**Comment by maokejackson** [comment]
The fixes work in my real project, thanks.
