### ISSUE TITLE
proguard-maven-plugin/pom.xml 2.1.1 contains version 2.1.2-SNAPSHOT

### ISSUE THREAD

**Issue by cap0** [wvengen/proguard-maven-plugin#94]
Plugin's descriptor contains the wrong version: 2.1.2-SNAPSHOT

**Comment by lasselindqvist** [comment]
I deleted the fault tag 2.1.1 that shouldn't have existed and changed the release to point to the correct tag.

**Comment by lasselindqvist** [comment]
Should be fine now. Also the artifact has been deployed to Central now.
