### ISSUE TITLE
How to Recursively read configs

### ISSUE THREAD

**Issue by MCMicS** [wvengen/proguard-maven-plugin#95]
The usage page says:
Recursively reads configuration options from the given file filename

It is possible to load configurations for single artifacts (dependencies) which will be merged to one or what is meaned with recursively?
```
My Scenario:
Project A
- src
  - proguard.conf
Project B
- src
  - proguard.conf
```
Project B -> Project A

If I want to obfuscated Project B the configuration of Project A will be load and the the Project B configuration.
I've tried assembly but this will obfuscate all with one configuration. I want to create the config per artifact

Is this possible?

**Comment by lasselindqvist** [comment]
What the parameter is doing, is just adding "-include" parameter for Proguard (https://www.guardsquare.com/en/products/proguard/manual/usage)
It seems to me that passing "proguard.conf" should do the trick, but if it doesn't, you can always define this plugin separately for each submodule and just have a different proguardInclude parameter.

**Comment by MCMicS** [comment]
Thanks. for answering
Whe proguard doc say nothing about recursive but I think my scenario is not possible.
the "-include" Parameter accepts variables with angular brackets
