### ISSUE TITLE
Publish 2.1.1 to central

### ISSUE THREAD

**Issue by cjgriscom** [wvengen/proguard-maven-plugin#96]
It looks like 2.1.0 is still the latest version on maven central.

**Comment by lasselindqvist** [comment]
Deployed it (properly) now. Should be usable with
<dependency>
  <groupId>com.github.wvengen</groupId>
  <artifactId>proguard-maven-plugin</artifactId>
  <version>2.1.1</version>
</dependency>
after some waiting period.

**Comment by lasselindqvist** [comment]
https://repo1.maven.org/maven2/com/github/wvengen/proguard-maven-plugin/2.1.1/ here it is.
